name: Netlify Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent infinite runs
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: true
        fetch-depth: 0  # Required for pushing commits

    - name: Check Netlify availability
      id: check_netlify
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      run: |
        # Check if Netlify is already building
        queue_status=$(curl -s -H "Authorization: Bearer $NETLIFY_TOKEN" \
          "https://api.netlify.com/api/v1/sites?filter=arham80-commits-react-new-project")
        
        if echo "$queue_status" | grep -q '"state": "building"'; then
          echo "status=queued" >> $GITHUB_OUTPUT
          echo "Netlify is busy. Will retry later."
          exit 1
        else
          echo "status=ready" >> $GITHUB_OUTPUT
        fi

    - name: Deploy to Netlify
      if: steps.check_netlify.outputs.status == 'ready'
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      run: |
        response=$(curl -m 300 -s -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $NETLIFY_TOKEN" \
          -d '{
            "siteName": "arham80-commits-react-new-project",
            "repoUrl": "https://github.com/arham80-commits/react-new-project",
            "branchName": "main",
            "publishDir": "dist",
            "functions_dir": "functions"
          }' \
          "https://api.netlify.com/api/v1/sites")
        
        echo "API Response: $response"
        
        if echo "$response" | grep -q '"id":'; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Smart retry on failure
      if: failure() && steps.check_netlify.outputs.status != 'ready'
      run: |
        echo "Netlify was busy. Waiting 10 minutes before retry..."
        sleep 600
        
        echo "Creating retry commit with [skip ci]"
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit --allow-empty -m "Retry Netlify deployment [skip ci]"
        git push origin main

    - name: Show final status
      run: |
        if [ "${{ steps.deploy.outputs.status }}" = "success" ]; then
          echo "Deployment initiated successfully"
        else
          echo "Will retry deployment after delay"
        fi
